import { expect, test } from './fixtures';

test('customer master lookup fills order details and dashboard shows product batch counts', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/login');
  await page.getByLabel('Email or phone number').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('local-test-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page).toHaveURL(/\/app$/);
  await page.goto('/app/orders');
  await page.getByRole('link', { name: '+ Add customer', exact: true }).click();
  await page.getByLabel('Customer name', { exact: true }).fill('Dashboard customer');
  await page.getByLabel('Contact name', { exact: true }).fill('Sample contact');
  await page.getByLabel('Email', { exact: true }).fill('pickup@example.test');
  await page.getByLabel('Phone', { exact: true }).fill('555-0123');
  await page.getByLabel('Address', { exact: true }).fill('100 Test Road');
  await page.getByLabel('Customer notes', { exact: true }).fill('Call before pickup');
  await page.getByRole('button', { name: 'Save customer', exact: true }).click();
  await expect(page).toHaveURL(/\/app\/customers\?customer=/);
  const customerUrl = page.url();
  await page.goto('/app/products');
  const options = page.locator('details.product-customer-options').first();
  await options.locator(':scope > summary').click();
  const add = options.locator('details').filter({ hasText: '+ Add customer option' });
  await add.locator('summary').click();
  await add.getByLabel('Customer', { exact: true }).fill('Dashboard customer');
  await add.getByLabel('Option name', { exact: true }).fill('2-gallon bag');
  await add.getByRole('combobox', { name: /^Packaging/ }).selectOption('custom');
  await add.getByLabel('Sales unit', { exact: true }).selectOption('bag');
  await add.getByLabel('Gallons per sales unit', { exact: true }).fill('2');
  await add.getByLabel('Price per unit (USD)', { exact: true }).fill('12.50');
  await add.getByRole('button', { name: 'Save customer option', exact: true }).click();
  await expect(options.getByText('Dashboard customer · 2-gallon bag · $12.50 / bag', { exact: true })).toBeVisible();
  await page.goto(customerUrl);
  await page.getByRole('link', { name: 'New order', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Selected customer details' })).toContainText('Call before pickup');
  await expect(page.getByRole('region', { name: 'Selected customer details' })).toContainText('100 Test Road');
  await page.getByLabel('Customer pickup date').fill('2026-10-01');
  await page.getByLabel('Customer order reference (optional)').fill('Pickup example');
  await page.getByLabel('Preview Italian dressing', { exact: true }).fill('3');
  await expect(page.locator('.order-product-line')).toContainText('$250.00 / 40-gallon batch');
  await expect(page.locator('.order-product-line')).toContainText('60 bag · $750.00');
  await page.getByRole('button', { name: 'Save order & estimate ingredients' }).click();
  await expect(page).toHaveURL(/\/app\/orders\?order=/);
  await expect(page.getByRole('table', { name: 'Ordered products' })).toContainText('$750.00');
  await page.goto(customerUrl);
  await expect(page.locator('.worksheet-links')).toContainText('Pickup Oct 1, 2026');
  await expect(page.locator('.worksheet-links')).toContainText('Ordered');
  await page.goto('/app');
  const pickups = page.locator('.dashboard-pickups');
  await expect(pickups).toContainText('Dashboard customer');
  await expect(pickups).toContainText('Preview Italian dressing');
  await expect(pickups).toContainText('3 batches');
  await expect(pickups).toContainText('3 total batches');
  const demand = page.locator('.dashboard-demand');
  await expect(demand).toContainText('2 ingredients short');
  await expect(demand).toContainText('Preview garlic powder');
  await expect(demand).toContainText('Preview lemon juice');
  await demand.getByRole('button', { name: 'Generate supplier purchase drafts' }).click();
  await expect(demand.getByRole('status')).toContainText('1 purchase drafts created.');
  await expect(demand.getByRole('button')).toBeDisabled();
  await page.reload();
  await demand.getByRole('button', { name: 'Generate supplier purchase drafts' }).click();
  await expect(demand.getByRole('status')).toContainText('0 purchase drafts created.');
  await expect(demand.getByRole('status')).toContainText('Review existing draft');
  await expect(demand.getByRole('button')).toHaveText('Generate supplier purchase drafts');
  await expect(page.locator('main'))
    .toContainText('Shipment confirmation is not available yet');
  const fits = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth);
  expect(fits).toBe(true);
  await page.screenshot({ path: info.outputPath('operations-dashboard.png'), fullPage: true });
  expect(errors).toEqual([]);
});
