import { expect, test } from './fixtures';

test('prepares customer production with paired batches, shortage review, revision and cancellation', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/login');
  await page.getByLabel('Email or phone number').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('local-test-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page).toHaveURL(/\/app$/);
  await page.goto('/app/orders');
  await page.getByLabel('Customer', { exact: true }).fill('Production customer');
  await page.getByLabel('Customer order reference (optional)').fill(`Production ${info.project.name}`);
  await page.getByLabel('Customer needs by').fill('2026-10-01');
  await page.getByLabel('Preview Italian dressing', { exact: true }).fill('4');
  await page.getByRole('button', { name: 'Save order & estimate ingredients' }).click();
  await expect(page).toHaveURL(/\/app\/orders\?order=/);
  const preparation = page.getByRole('region', { name: 'Production preparation', exact: true });
  await expect(preparation).toContainText('Not planned');
  await preparation.getByLabel('Start / ingredients ready by').fill('2026-09-28');
  await preparation.getByLabel('Planned completion').fill('2026-09-30');
  await preparation.getByRole('button', { name: 'Save production draft' }).click();
  await expect(preparation.locator('.badge')).toHaveText('Draft');
  await preparation.getByText('View mixer batches & spice preparations', { exact: true }).click();
  await expect(preparation.locator('.production-batch')).toHaveCount(4);
  await expect(preparation.locator('.production-batch').first()).toContainText('SP-');
  await expect(page.getByText('Availability checked for production start:', { exact: false })).toBeVisible();
  await preparation.getByRole('button', { name: 'Confirm production preparation', exact: true }).click();
  await expect(preparation.getByRole('status')).toContainText('Explain how ingredient shortages');
  await preparation.getByLabel('How shortages will be resolved (if any)')
    .fill('Expedite ingredients with supplier before production');
  await preparation.getByRole('button', { name: 'Confirm production preparation', exact: true }).click();
  await expect(preparation.locator('.badge')).toHaveText('Confirmed');
  await page.screenshot({ path: info.outputPath('order-production-confirmed.png'), fullPage: true });
  await preparation.getByLabel('Start / ingredients ready by').fill('2026-09-29');
  await preparation.getByRole('button', { name: 'Save production draft' }).click();
  await expect(preparation.getByRole('status')).toContainText('Enter a reason');
  await preparation.getByLabel('Notes / reason for change').fill('Supplier delivery moved one day');
  await preparation.getByRole('button', { name: 'Save production draft' }).click();
  await expect(preparation.locator('.badge')).toHaveText('Draft');
  await expect(preparation.locator('.production-batch')).toHaveCount(4);
  await preparation.getByLabel('Notes / reason for change').fill('Customer requested a revised order');
  await preparation.getByRole('button', { name: 'Cancel production preparation', exact: true }).click();
  await expect(preparation.locator('.badge')).toHaveText('Cancelled');
  await expect(preparation.locator('.production-batch')).toHaveCount(4);
  expect(errors).toEqual([]);
  const fits = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth);
  expect(fits).toBe(true);
});
